theme: jekyll-theme-minimal

title: N. Emrah Aydinonat

description: |

  Faculty of Social Sciences, University of Helsinki
  
  ğŸ¥¼ Researcher @ [TINT](http://tint.helsinki.fi/)
  
  ğŸ“˜ Editor @ [Journal of Economic Methodology](https://www.tandfonline.com/toc/rjec20/current)
  
  
  ğŸ”— [Website](http://neaydinonat.com) (Wordpress.com site, soon to be abandoned)
  
  ğŸš§ [Website on Github](http://aydinonat.github.io/academic)
  
  
  ğŸ¦ [@aydinonat](https://twitter.com/aydinonat) 
  
  ğŸ¦ [@iktisatnedir](https://twitter.com/iktisatnedir) (in Turkish)
